# Generated by Django 2.2.7 on 2021-05-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERACCOUNT',
            fields=[
                ('USERNAME', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_NAME', models.CharField(default='', max_length=254)),
                ('PASSWORT', models.CharField(default='', max_length=254)),
                ('SICHERHEITSFRAGE1', models.TextField(default='')),
                ('SICHERHEITSFRAGE2', models.TextField(default='')),
                ('SICHERHEITSANTWORT1', models.TextField(default='')),
                ('SICHERHEITSANTWORT2', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='KATHEGORIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KATEGORIE_TITEL', models.CharField(default='', max_length=254)),
                ('USERNAME', models.ManyToManyField(to='mind.USERACCOUNT')),
            ],
        ),
        migrations.CreateModel(
            name='EINTRAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EINTRAG_TITEL', models.CharField(default='', max_length=254)),
                ('EINTRAG_BESCHREIBUNG', models.TextField(default='')),
                ('AUDIO', models.FileField(blank=True, upload_to='')),
                ('AUDIOTEXT', models.TextField(blank=True, default='')),
                ('BILD', models.ImageField(blank=True, upload_to='')),
                ('KATEGORIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mind.KATHEGORIE')),
            ],
        ),
    ]
