# Generated by Django 2.2.7 on 2021-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kathegorie',
            name='EINTRAG',
            field=models.TextField(blank=True, default=''),
        ),
    ]
