# Generated by Django 2.2.7 on 2021-05-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_kathegorie_eintrag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kathegorie',
            old_name='EINTRAG',
            new_name='BESITZER',
        ),
    ]
