# Generated by Django 2.2.7 on 2021-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0003_auto_20210524_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.TextField(blank=True, default=''),
        ),
    ]
