# Generated by Django 2.2.7 on 2021-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0005_auto_20210529_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIO',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIOTEXT',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.TextField(default=''),
        ),
    ]
