# Generated by Django 2.2.7 on 2021-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0006_auto_20210529_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIO',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIOTEXT',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
