# Generated by Django 2.2.7 on 2021-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0008_auto_20210529_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIO',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
