# Generated by Django 2.2.7 on 2021-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0009_auto_20210531_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIO',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
