# Generated by Django 2.2.7 on 2021-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0010_auto_20210601_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIO',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
