# Generated by Django 2.2.7 on 2021-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0011_auto_20210601_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='AUDIO',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='BILD',
            field=models.TextField(blank=True, default=''),
        ),
    ]
