# Generated by Django 2.2.7 on 2021-06-05 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0012_auto_20210601_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='eintrag',
            name='CREATED_AT',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kathegorie',
            name='CREATED_AT',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
