# Generated by Django 2.2.7 on 2021-06-05 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0014_auto_20210605_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='CREATED_AT',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
